name: Plugin WordPress.org asset/readme update
on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths:
            - "readme.txt"
            - ".wordpress-org/**"

jobs:
    update:
        name: Update
        runs-on: ubuntu-latest

        steps:
            - name: Check out Git repository
              uses: actions/checkout@v2

            - name: WordPress.org plugin asset/readme update
              uses: wearerequired/action-wordpress-plugin-asset-update@copy-only
              env:
                  SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
                  SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
                  SLUG: good-slider
